config/routes.rb
Dans::Application.routes.draw do
  resources :photos


  get "pages/about"

  devise_for :users

  resources :blogs
  get 'blogs/:id/:slug' => 'blogs#show', as: 'blog_with_slug'
  post 'blogs/preview' => 'blogs#preview'

  root :to => 'blogs#index'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :title, :published

  validates_presence_of :content
  validates_presence_of :title
  validates_inclusion_of :published, in: [true, false]

  def summary(length=250)
    content[0, length]
  end

  def slug
    title.downcase.gsub(" ", "-")
  end
end

app/models/photo.rb
require "open-uri"

class Photo < ActiveRecord::Base
  attr_accessor :url
  attr_accessible :caption, :image, :url
  has_attached_file :image,
    :styles => {
      :medium_square => "300x300#",
      :small_square => "100x100#",
      :medium => "300x300>",
      :small => "100x100>"
    },
    :default_url => "/images/:style/missing.png"

  def image_from_url(url)
    self.image = open(url)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  def self.admin_emails
    ['goggin13@gmail.com', 'danstipanuk@gmail.com']
  end

  def admin?
    self.class.admin_emails.include? email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include BlogsHelper
  protect_from_forgery
  before_filter :load_recent_posts

  def load_recent_posts
    @recent = Blog.order('created_at desc').limit(3).all
  end

  def admin_only!
    unless signed_in? && current_user.admin?
      redirect_to root_path, flash: { error:  "You are not authorized at #{request.fullpath}"}
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_filter :admin_only!, except: [:index, :show]

  # GET /blogs
  # GET /blogs.json
  def index
    @first = Blog.where('published = true').order('created_at desc').first
    @blogs = Blog.where('published = true').order('created_at desc').offset(1).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Deleted #{@blog.title}." }
      format.json { head :no_content }
    end
  end

  def preview
    @text = params[:text]
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_filter :admin_only!

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    @photo.image_from_url(params[:photo].delete(:url)) if params[:photo][:url].present?

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    @photo.image_from_url(params[:url]) if params[:url].present?

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def link_to_blog(blog, options={})
    title = options.delete(:title) || blog.title
    link_to title, blog_with_slug_path({id: blog.id, slug: blog.slug}), options
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/blogs/_blog.html.erb
<% if signed_in? && current_user.admin? %>
  <%= link_to "Edit", edit_blog_path(blog), class: 'float-right' %>
<% end %>

<h2 class="title">
  <%= blog.title %>
</h2>

<div class="fb-like" 
     data-href="<%= blog_url(blog) %>"
     data-width="450" 
     data-show-faces="true" 
     data-colorscheme="dark"
     data-send="true"></div>

<%= BlueCloth.new(blog.content).to_html.html_safe %>


<div class="fb-like" 
     data-href="<%= blog_url(blog) %>"
     data-width="450" 
     data-show-faces="true" 
     data-colorscheme="dark"
     data-send="true"></div>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>
  <div id='blog_preview'>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/_summary.html.erb
<div class='blog_summary'>
  <%= blog.summary %>... 
</div>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Delete Blog', @blog, method: :delete, confirm: "Really Delete #{@blog.title}?" %> | 
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% if @first %>
  <%= render @first %>
<% end %>

<ul class="style1">
  <% @blogs.each do |blog| %>
    <li>
      <h3><%= blog.title %></h3>
      <p>
        <%= BlueCloth.new("#{blog.summary}...").to_html.html_safe %>
      </p>
      <p><%= link_to_blog blog, title: "Read More", class: 'button-style' %></p>
      <% if signed_in? && current_user.admin? %>
        <p><%= link_to "Edit", edit_blog_path(blog), class: 'button-style' %></p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/preview.js.erb
var html = '<%= j( BlueCloth.new(@text).to_html.html_safe ) %>';
$('#blog_preview').html(html);

app/views/blogs/show.html.erb
<%= render @blog %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Conventional 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130128

-->
<html>
  <head>
    <title>DapperDan</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href='http://fonts.googleapis.com/css?family=Archivo+Narrow:400,700|Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
  </head>
  <body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=357103551019569";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <div id="wrapper">

     <%- flash.each do |name, msg| -%>
       <%= content_tag :div, msg, :class => 'flash', :id => "flash_#{name}" if msg.is_a?(String) %>
     <%- end -%> 

      <div id="header-wrapper">
        <div id="header" class="container">
          <div id="logo">
            <% 4.times do %>
              <%= link_to image_tag("dapperdan.jpg", :border => 0), root_path %>
            <% end %>
          </div>
          <div id="menu">
            <ul>
              <li class="<%= request.fullpath == '/' ? 'active' : '' %>">
                <%= link_to 'Posts', root_path %>
              </li>
              <li class="<%= request.fullpath =~ /pages\/about/ ? 'active' : '' %>">
                <%= link_to 'About', pages_about_path %>
              </li>
              <% if user_signed_in? && current_user.admin? %>
                <li class="<%= request.fullpath =~ /blogs\/new/ ? 'active' : '' %>">
                  <%= link_to 'New Blog', new_blog_path %>
                </li>
                <li class="<%= request.fullpath =~ /photos/ ? 'active' : '' %>">
                  <%= link_to 'Photos', photos_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div id="banner" class="container">
      </div>

      <div id="page" class="container">
        <div id="content">
          <div id="box1">
            <%= yield %>
          </div>
        </div>

        <div id="sidebar">
          <h2>Recent</h2>
          <ul class="style3">
            <% @recent.each do |post| %>
              <li>
                <p>
                  <%= link_to_blog post %>
                </p>
                <p class="date">
                  <%= post.created_at.strftime("%m-%d-%Y") %>
                </p>
              </li>
            <% end %>
          </ul>
        </div>


      </div>
    </div>

    <div id="footer">
      <p>Copyright (c) 2013 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a>. Photos by <a href="http://fotogrph.com/">Fotogrph</a>.</p>
    </div>

  </div>

  <% if user_signed_in? %>
    <%= link_to 'logout', destroy_user_session_path, method: :delete %>
  <% else %>
    <a href='<%= new_user_session_path %>'>
      <%= image_tag 'keychain_small.png', id: 'login_icon' %>
    </a>
  <% end %>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<div id='about-page'>
  
  <%= image_tag 'dan.jpg', :id => 'about-headshot' %>

  <p>
  Wow my very own website.  Really, how many people can say that? According to Google, a lot, apparently.  This is my blog dedicated to all the things I love: music, movies, sports, technology, politics, vegan cuisine, sarcasm, cats, parentheses, and pictures of cats acting like people (seriously check it out). Oh, and string theory.  So thanks very much for visiting my page of wonders.  I know there a lot of other options out there, but I truly hope to find a sliver of room in the heart of your digital kingdom.  If not, I can always just put porn up instead. Come on, dare me!
  </p>

  <p>
  I also hope this blog will serve as a time capsule, minus the hassle/complete waste of time of actually burying a time capsule.  Really, I can’t wait for the day when my children and my children’s children can see how much free time I had to rant about Breaking Bad and new Arcade Fire albums instead of building them any resemblance of an inheritance.  No worries Future Children! I probably would have wasted any inheritance on short-sighted business ventures anyway. And really, I don’t care if that’s comforting or not since you’re all probably living on a sweet ass Moon colony by now. So go take your bionic exoskeletons and get a job.
  </p>
 
  <p>
  Anyway, I’d like to give thanks to some very special people who’ve helped me along the way. Thanks to my family, Liz L., Aidan, Allison, Kari, Jacob, Mike, AZ, Malia Obama, Lost seasons 1 through 3, and all parties involved in Pacers-Pistons’ Malice in the Palace©. A very special thanks to <%= link_to 'Matt aka Goggins', 'http://www.mattgoggin.com/', target: '_blank' %> aka Dirty Dog Johnson, The Roommate, the Badger to my Skinny Pete (Aidan is Combo). Oh, and he’s the dude who actually put this website together (like with the code and stuff. You know, source codes in the matrix and whatnot. It’s all very technical). Thanks bro, and sorry I ate the last banana. Let’s DO THIS!
  </p>

</div>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url%>
  </div>

  <%= f.file_field :avatar %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
<% @photos.each do |photo| %>
  <tr>
    <td><%= image_tag photo.image(:small_square) %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caption:</b>
  <%= @photo.caption %>
</p>

<%= image_tag @photo.image.url(:medium_square) %>
<%= image_tag @photo.image.url(:small_square) %>
<%= image_tag @photo.image.url(:medium) %>
<%= image_tag @photo.image.url(:small) %>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>